# Generated by Django 4.2 on 2023-05-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="have_permission",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
