# Generated by Django 4.2 on 2023-05-02 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_have_permission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="have_permission",
        ),
    ]
