# Generated by Django 4.2 on 2023-05-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_have_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="have_permission",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="library_collaborator",
            field=models.BooleanField(default=True),
        ),
    ]
