# Generated by Django 4.2 on 2023-05-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_have_permission_alter_user_library_collaborator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="library_collaborator",
            field=models.BooleanField(default=False),
        ),
    ]
