# Generated by Django 4.2 on 2023-05-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("return_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "book_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="copies.copy"
                    ),
                ),
            ],
        ),
    ]
