# Generated by Django 4.2 on 2023-05-02 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("copies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copy",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="loan",
            field=models.ManyToManyField(
                related_name="loan", through="copies.Loan", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
