# Generated by Django 4.2 on 2023-05-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="return_date",
            field=models.DateField(null=True),
        ),
    ]
